### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by brunocalado** [Lefteous/loaded-dice-roll#4]
Hi

Can you allow this module to be called by a macro?

Thank you.

**Comment by jnicholCU** [comment]
Yeah sure thing. Will try and get that added to my next patch.

**Comment by Lefteous** [comment]
Yeah sure thing. Will try and get that added to my next patch.

**Comment by Lefteous** [comment]
@brunocalado 
Let me know if the macro updates work for you and was what you were hoping for. 
I've outlined some info in the [readme](https://github.com/Lefteous/loaded-dice-roll/tree/v1.0.2?tab=readme-ov-file#macros)

**Comment by brunocalado** [comment]
> @brunocalado Let me know if the macro updates work for you and was what you were hoping for. I've outlined some info in the [readme](https://github.com/Lefteous/loaded-dice-roll/tree/v1.0.2?tab=readme-ov-file#macros)

Thank you very much.

Is it possible to add a simple description to:
```
+
-
*
/

=, ==, ===, eq
>, gt
>=, gte
<, lt
<=, lte
```
